FIND_PATH(IRRLICHT_INCLUDE_DIR irrlicht.h
	PATHS ${CMAKE_CURRENT_SOURCE_DIR}/extlibs/irrlicht-1.8.4/include
	PATH_SUFFIXES irrlicht
)

MESSAGE(STATUS "IRRLICHT_INCLUDE_DIR = ${IRRLICHT_INCLUDE_DIR}")

FIND_LIBRARY(IRRLICHT_LIBRARY NAMES Irrlicht
   PATHS ${CMAKE_CURRENT_SOURCE_DIR}/extlibs/irrlicht-1.8.4/lib
	 PATH_SUFFIXES Linux Win32-gcc
	 NAMES Irrlicht
	 			 libIrrlicht.a
)

MESSAGE(STATUS "IRRLICHT_LIBRARY = ${IRRLICHT_LIBRARY}")

# handle the QUIETLY and REQUIRED arguments and set IRRLICHT_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IRRLICHT DEFAULT_MSG IRRLICHT_LIBRARY IRRLICHT_INCLUDE_DIR)

IF(IRRLICHT_FOUND)
  SET(IRRLICHT_LIBRARIES ${IRRLICHT_LIBRARY})
ELSE(IRRLICHT_FOUND)
  SET(IRRLICHT_LIBRARIES)
ENDIF(IRRLICHT_FOUND)

MARK_AS_ADVANCED(IRRLICHT_LIBRARY IRRLICHT_INCLUDE_DIR)
